import Container from '@/componnent/Container';
import Head from 'next/head';
import { UsesContext } from '../../context/Context';
import styles from "../styles/Home.module.css";

export default function Home() {


  const { url } = UsesContext();

  console.log(url);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <Container>
          <div className={styles.imgWrp}>
            {/* <Image className={styles.img} src={img} /> */}
            <iframe className={styles.img} src={url}></iframe>
          </div>
        </Container>
      </main>
    </>
  )
}
