import Container from '@/componnent/Container';
import Head from 'next/head';
import Image from 'next/image';
import { UsesContext } from '../../context/Context';
import img from "../../public/BD_Map_admin.svg";
import styles from "../styles/Home.module.css";


export default function Home() {


  const { url } = UsesContext();

  console.log(url);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <Container>
          <div className={styles.imgWrp}>
            {url === "" ? < Image className={styles.img} src={img} /> : <iframe height="100" className={styles.ifram} src={`https://${url}`}></iframe>}
          </div>
        </Container>
      </main>
    </>
  )
}
